
services:
  backend:
    build: ./Backend
    ports:
      - "5030:5030"
    environment:
      - MONGODB_URI=mongodb+srv://durangoesteban456:1151444098Je.@cluster0.lm2z1.mongodb.net/librovisitas?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5030
    env_file:
      - ./Backend/.env

  frontend:
    build: ./Frontend
    ports:
      - "3030:80"