
services:
  backend:
    build: ./Backend
    ports:
      - "5050:5050"
    environment:
      - MONGODB_URI=mongodb+srv://durangoesteban456:1151444098Je.@cluster0.lm2z1.mongodb.net/librovisitas?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5000
    env_file:
      - ./Backend/.env

  frontend:
    build: ./Frontend
    ports:
      - "3050:3050"